### PR TITLE
Added new custom errors and example

### PR DESCRIPTION
**Pull request by grantcarthew**
I just saw the gh-pages-next branch, so I don't know if this is needed or not?

### CODE REVIEW

**Comment by grantcarthew** [comment]
Hey @neumino, I have come across an error in my code and it is because I am using Node v0.12 promises mixed with Bluebird promises. As far as I can see, Node promises don't support error types. Is this correct? If this is the case, then maybe the code examples should be moving the error type checks into the catch function rather than relying on Bluebird.

Here is the example I am using:
```
// This function returns a node promise
VerifyAuthToken().then(result => {
  return UserModel.get('invalid id as an example').run()
}).catch(errors.DocumentNotFound, err => {
  // This handler is not being called because node promises don't support types.
}).catch(err => {
 // Unexpected error handler.
  // Should we do type checking here? It would be better supported.
})

```

**Comment by grantcarthew** [comment]
So I just tested this in a single catch block:
```js
    if (err instanceof errors.DocumentNotFound) {
      logger.debug('Bingo')
    }
```
Works fine.

**Comment by grantcarthew** [comment]
Maybe now that node fully supports Promises thinky could move away from Bluebird?

**Comment by neumino** [comment]
Hey @grantcarthew! Thanks for the PR! It looks good. `gh-pages-next` is just an old branch.

Yes natives promises don't support `catch(predicate, handler)`. I don't plan to move to native promises mostly because the native implementation is actually slower than bluebird, so I see very little benefits from doing so. All the features available in native promises are already available in bluebird if I'm not mistaken.

**Comment by grantcarthew** [comment]
Ok, I didn't know that about Bluebird. I will switch to using it myself. Thanks.
I just looked at the page and the bullet points didn't work. Not sure why. It could be the lack of a blank line before the first hypen.

Do you want me to try and fix it? I don't want to cause you more work mate.

**Comment by neumino** [comment]
No worries, I just pushed a fix, it was just missing a line. Thanks for your help!

**Pull request merged**
