### PR TITLE
New Error Type: ValidationError

### PR DESCRIPTION
**Pull request by primitive-type**
It would be helpful to have a new error type for validation errors, similar to the ```DocumentNotFound``` error type defined in https://github.com/neumino/thinky/blob/master/lib/errors.js

The use case I am imagining is for HTTP status code responses in a RESTful API. You could more granularly report to the API consumer whether an error was their fault due to submission of bad data which the thinky model rejects (400), a particular document not being found (404 - which the ```DocumentNotFound``` type is already helpful for), or some other failure (500). 

I believe this new error could be thrown instead of the more generic Error type in https://github.com/neumino/thinky/blob/master/lib/schema.js

If you think this makes sense, I would be happy to try my hand at a pull request for this.

Thanks!

### CODE REVIEW

**Comment by primitive-type** [comment]
I think I caught all instances where a `ValidationError` should be returned instead of a generic one. Let me know if there was anything I missed.

**Comment by neumino** [comment]
Ok, this should be in branch `next` with https://github.com/neumino/thinky/pull/195
I'll write some docs and release it tomorrow or this week end.

Thanks @primitive-type :)

**Comment by primitive-type** [comment]
@neumino Great. Thanks for thinky! It has been a real joy to use.

**Comment by neumino** [comment]
Released in 1.16.7, thanks again @primitive-type :)

**Pull request merged**
